"""empty message

Revision ID: 0147a5b4281b
Revises: 
Create Date: 2025-07-25 16:36:53.349104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0147a5b4281b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dish_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('preparation_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('dish_category_id', sa.Integer(), nullable=True),
    sa.Column('preparation_category_id', sa.Integer(), nullable=True),
    sa.Column('profit_type', sa.String(length=20), nullable=False),
    sa.Column('profit_value', sa.Float(), nullable=False),
    sa.Column('is_preparation', sa.Boolean(), nullable=False),
    sa.Column('yield_quantity', sa.Float(), nullable=True),
    sa.Column('yield_unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dish_category_id'], ['dish_category.id'], ),
    sa.ForeignKeyConstraint(['preparation_category_id'], ['preparation_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dish_is_preparation'), ['is_preparation'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('package_weight', sa.Float(), nullable=True),
    sa.Column('package_unit', sa.String(length=50), nullable=False),
    sa.Column('package_price', sa.Float(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('article_number', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('parent_dish_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('preparation_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(product_id IS NOT NULL AND preparation_id IS NULL) OR (product_id IS NULL AND preparation_id IS NOT NULL)', name='chk_ingredient_source'),
    sa.ForeignKeyConstraint(['parent_dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['preparation_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    op.drop_table('product')
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_is_preparation'))

    op.drop_table('dish')
    op.drop_table('supplier')
    op.drop_table('preparation_category')
    op.drop_table('dish_category')
    op.drop_table('category')
    # ### end Alembic commands ###
